import { useRef, useEffect } from "react";
import { Box, Typography } from "@mui/material";

const infographicStyles = `
.infographic-wrap {
  width:min(1100px,92vw); 
  padding:16px 8px 32px;
  margin:auto;
}
.flow {
  display:grid; 
  grid-template-columns:1fr; 
  grid-template-rows:auto 90px auto; 
  gap:0; 
  align-items:center; 
  justify-items:center;
}
.row-top {
  grid-row:1; grid-column:1; 
  display:flex; 
  justify-content:center; 
  align-items:center; 
  gap:0;
}
.circle {
  width:clamp(260px,34vw,460px); 
  aspect-ratio:1/1; 
  border-radius:999px;
  background:radial-gradient(120% 120% at 70% 30%, #4faf53, #2f6b43);
  box-shadow:0 10px 30px rgba(0,0,0,.08);
  border:1px solid #d7e1dc;
  display:flex; align-items:center; justify-content:center;
  text-align:center; padding:16px; color:#fff;
  opacity:0;
  transition:opacity .8s, transform .8s;
}
.circle--light {
  background:radial-gradient(120% 120% at 70% 30%, #6bd16c, #4faf53);
}
.circle h2 {
  font-size:clamp(18px,2.6vw,28px); line-height:1.25; margin:0; font-weight:800;
}
.circle p {
  font-size:clamp(15px,2.1vw,22px); line-height:1.35; margin:10px 0 0;
}
.arrow {
  grid-row:2; grid-column:1; width:0; height:0; 
  border-left:18px solid transparent; 
  border-right:18px solid transparent; 
  border-top:26px solid #202427; 
  filter:drop-shadow(0 6px 10px rgba(0,0,0,.08)); 
  opacity:0; 
  transform:translateY(-6px);
  transition:opacity .5s, transform .5s;
}
.bottom {
  grid-row:3; grid-column:1;
}
.from-left.show  { opacity:1; transform:none; animation:slideInLeft .8s cubic-bezier(.2,.9,.2,1) forwards; }
.from-right.show { opacity:1; transform:none; animation:slideInRight .8s cubic-bezier(.2,.9,.2,1) forwards; }
.arrow.show      { opacity:1; transform:none; animation:pop .5s ease-out forwards; }
.bottom.show     { opacity:1; transform:none; animation:riseIn .7s ease-out forwards; }

@keyframes slideInLeft { from{opacity:0; transform:translateX(-40vw) scale(.98)} to{opacity:1; transform:translateX(0) scale(1)} }
@keyframes slideInRight{ from{opacity:0; transform:translateX(40vw) scale(.98)}  to{opacity:1; transform:translateX(0) scale(1)} }
@keyframes pop          { from{opacity:0; transform:translateY(-6px)} to{opacity:1; transform:translateY(0)} }
@keyframes riseIn       { from{opacity:0; transform:translateY(16px) scale(.96)} to{opacity:1; transform:translateY(0) scale(1)} }

@media (max-width:900px){
  .flow{ grid-template-rows:auto 60px auto }
  .row-top{ flex-direction:column; gap:0 }
  @keyframes slideInLeft { from{opacity:0; transform:translateY(-30vh) scale(.98)} to{opacity:1; transform:translateY(0) scale(1)} }
  @keyframes slideInRight{ from{opacity:0; transform:translateY(-15vh) scale(.98)} to{opacity:1; transform:translateY(0) scale(1)} }
}
`;

export function InfographicSection() {
  const sectionRef = useRef<HTMLDivElement | null>(null);
  const c1Ref = useRef<HTMLDivElement | null>(null);
  const c2Ref = useRef<HTMLDivElement | null>(null);
  const arrowRef = useRef<HTMLDivElement | null>(null);
  const c3Ref = useRef<HTMLDivElement | null>(null);
  const hasAnimated = useRef(false);

  useEffect(() => {
    // Inject styles
    if (!document.getElementById("infographic-section-styles")) {
      const style = document.createElement("style");
      style.id = "infographic-section-styles";
      style.innerHTML = infographicStyles;
      document.head.appendChild(style);
    }

    // Intersection Observer for scroll-triggered animation
    const observer = new window.IntersectionObserver(
      (entries) => {
        const entry = entries[0];
        if (entry.isIntersecting && !hasAnimated.current) {
          hasAnimated.current = true;
          // Sequential animation
          setTimeout(() => c1Ref.current?.classList.add("show"), 0);
          setTimeout(() => c2Ref.current?.classList.add("show"), 200);
          setTimeout(() => arrowRef.current?.classList.add("show"), 1000);
          setTimeout(() => c3Ref.current?.classList.add("show"), 1600);
        }
      },
      { threshold: 0.3 }
    );

    if (sectionRef.current) {
      observer.observe(sectionRef.current);
    }

    return () => observer.disconnect();
  }, []);

  return (
    <Box component="div" className="infographic-wrap" ref={sectionRef} sx={{borderRadius: 4, background: "#f7f8f9", mt: 8}}>
      <Box className="flow" component="section" aria-label="Infographie animée">
        <Box className="row-top" component="div">
          <Box
            ref={c1Ref}
            className="circle from-left"
            component="figure"
          >
            <figcaption>
              <Typography component="h2">
                Carbon footprint generated by electricity consumption in Quebec
              </Typography>
              <Typography component="p">
                1.2 à 1.7 g CO₂/kWh
              </Typography>
            </figcaption>
          </Box>
          <Box
            ref={c2Ref}
            className="circle circle--light from-right"
            component="figure"
          >
            <figcaption>
              <Typography component="h2">
                Energy consumption for greenhouse heating in Quebec
              </Typography>
              <Typography component="p">
                650 à 850 kWh/m²·year
              </Typography>
            </figcaption>
          </Box>
        </Box>
        <Box
          ref={arrowRef}
          className="arrow"
          component="div"
          aria-hidden="true"
        />
        <Box
          ref={c3Ref}
          className="circle circle--light bottom"
          component="figure"
        >
          <figcaption>
            <Typography component="h2">
              730 kWh/m²·year for a 1,750 m² greenhouse in Saint‑Hyacinthe
            </Typography>
          </figcaption>
        </Box>
      </Box>
    </Box>
  );
}